POST http://localhost:3000/api/comment/3
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJib2JAYm9iLmNvbSIsImlhdCI6MTY4ODYxMjkwNH0.qJ9rtgOGE5pKSrXs0SdMGUzdq1jRwJ4mG-B0OdVFpKA

{
  "content": "first comment"
}